name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Secret scan
        run: |
          npm install -g git-secrets
          git secrets --register-aws
          git secrets --add 'sk_live_[0-9a-zA-Z]{24}' # Stripe secret key
          git secrets --add 'pk_live_[0-9a-zA-Z]{24}' # Stripe publishable key
          git secrets --add 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9' # Supabase JWT pattern
          npx git-secrets --scan
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Type check
        run: pnpm tsc --noEmit
      - name: Build
        run: pnpm run build
      - name: Run Playwright E2E tests
        env:
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
        run: npx playwright test --config=playwright.config.ts
      - name: Run Jest unit tests
        run: pnpm test
